### ISSUE TITLE
ApproovURLSession EXC_BREAKPOINT (code=1, subcode=0x1b3dd1140)

### ISSUE THREAD

**Issue by JohanAlbrectsen** [approov/quickstart-ios-swift-urlsession#2]
Hi,
When firing a request using `ApproovURLSession`, I get the following error: 

`Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1b3dd1140)`

My App Delegate looks like this: 

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        do {
            let config = "#xxxx#HF+yyyyyyyyyyyy"
            try Approov.initialize(config, updateConfig: "auto", comment: nil)
        } catch let error {
            print("APPROOV ERROR: ", error)
        }
...
```

I've written a generic method, that should work with all types of requests:

```swift
func fire<T: Codable>(request: URLRequest, receiverModel: T.Type, completion: @escaping (Result<T, Error>) -> ()) {
        ApproovURLSession(configuration: .default).dataTask(with: request) { data, response, error in
            if let apiError = self.validateResponse(response: response, data: data) {
                DispatchQueue.main.async { completion(.failure(ApiError.appServerError(apiError))) }
            } else if let error = error {
                DispatchQueue.main.async { completion(.failure(error)) }
            } else if let data = data {
                if data.isEmpty, let t = EmptyApiResponse(message: "Ok") as? T {
                    DispatchQueue.main.async { completion(.success(t)) }
                } else {
                    do {
                        let object = try self.jsonDecoder.decode(T.self, from: data)
                        DispatchQueue.main.async { completion(.success(object)) }
                    } catch let error {
                        print("Decoding Error: ", error, "trying to decode: ", T.self)
                        DispatchQueue.main.async { completion(.failure(error)) }
                    }
                }
            } else {
                DispatchQueue.main.async { completion(.failure(ApiError.unknown)) }
            }
            
        }.resume()
    }
```

Here's a screenshot of the debug navigator:

![Screenshot 2023-02-08 at 20 36 38](https://user-images.githubusercontent.com/109629518/217633683-b8f331e8-e5fb-4f06-aaf0-22493a8c67de.png)

I really hope this can be resolved soon, our business is dependant on it!
Kind regards,

**Comment by ivolz** [comment]
Hi Johan,

I am very sorry you are having an issue. Could you please change the initialiser above to use the ApproovService version, like so:

try! ApproovService.initialize("<enter-your-config-string-here>")
let session = ApproovURLSession(URLSessionConfiguration.default)

There is an lldb_unnamed_symbol in the stack trace which might be an ApproovService or ApproovURLSession object but is very hard to know. Could you let me know if the above fix works for you?

Thanks,
Ivo

**Comment by ivolz** [comment]
@JohanAlbrectsen  pacibsp is a pointer authentication instruction. We do not support arm64e architecture but I am not sure if it is something that needs to be set in the swift pm config file. Could I ask you to check if you are running your device in arm64 mode (as opposite to arm64e)?
Please, let me know.

**Comment by ivolz** [comment]
@JohanAlbrectsen In my Xcode version the swift package manager behaves correctly and complains if trying to run on arm64e. If you still have not solved the issue, could you please let the app crash and send me a stack trace? Also what version of Xcode are you using. Thanks.

**Comment by ivolz** [comment]
Hi @JohanAlbrectsen,

this does look like something related to KVO implementation, which we do use. I need to try and reproduce it. I really need a favour from you in order to be able to understand the crash itself: would it be possible to follow the instruction in `Create a crash report while debugging` from this link https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs and attach the crash log so I can symbolicate it with the debug symbols and find the exact crash location? This would help enormously. I will try to reproduce this meanwhile somehow. Thank you for the understanding and apologies for the issue.

Ivo

**Comment by ivolz** [comment]
@JohanAlbrectsen Thank you very much! I will look at at it asap. Just to confirm from the crash log, the crash is in the main thread which is the UI one. Have you tested the abb before without Approov and you had no issues? Is your networking code executed in a different thread than the main one?

Thanks,
Ivo

**Comment by ivolz** [comment]
It should do, correct. I am asking just so I understand the context and can
troubleshoot and try to reproduce myself. Thanks.
-- 



Ivo Liondov

Test Engineer

Approov Mobile Security



***@***.***
approov.io

**Comment by ivolz** [comment]
@JohanAlbrectsen We have found the problem. We use KVO to keep track and modify the request headers. This, unfortunately causes an issue if the objects we observe are used within a closure/block. We still need to implement a solution and test it. Until we do so, the solution would be to create/access the ApproovURLSession.dataTask() methods from outside a closure. I understand it might be inconvenient. We are actively working on a solution but I can not give you an estimate time of completion.

**Comment by ivolz** [comment]
@JohanAlbrectsen We are implementing a solution now. Needs to be tested. If all works well perhaps Tuesday? This is very speculative.

**Comment by ivolz** [comment]
No problem, glad I could help!
-- 



Ivo Liondov

Test Engineer

Approov Mobile Security



***@***.***
approov.io
