### ISSUE TITLE
Crash in `ApproovURLSession`

### ISSUE THREAD

**Issue by JohanAlbrectsen** [approov/quickstart-ios-swift-urlsession#3]
Hey,
We're experiencing some crashes, which seems likely to be inside the `ApproovURLSession`. I've attached a crash-log, could we get you to take a look at it and confirm whether or not this is on Approov's side or our side?

Kind regards
[2023-04-23_16-25-48.4928_+0200-cbf2da3747d93117a67b9196bf63464e8d965bae.crash.zip](https://github.com/approov/quickstart-ios-swift-urlsession/files/11469817/2023-04-23_16-25-48.4928_%2B0200-cbf2da3747d93117a67b9196bf63464e8d965bae.crash.zip)

**Comment by JohanAlbrectsen** [comment]
I can confirm this is within the `ApproovURLSession`.

![Screenshot 2023-05-13 at 16 55 25 (2)](https://github.com/approov/quickstart-ios-swift-urlsession/assets/109629518/cca9ada2-6ae2-4df9-8371-342e6b928d75)

**Comment by JohanAlbrectsen** [comment]
It seems to happen on devices which are a little older. It can be reproduced on iPhone 7 at the moment, but not on iPhone 11 Pro.

**Comment by richardmtaylor** [comment]
Thanks, we will investigate

**Comment by ivolz** [comment]
Hi @JohanAlbrectsen, there was a bug in our side which we fixed in the 3.1.4 version of the swift package. Could you please update and let us know! Thank you.

**Comment by JohanAlbrectsen** [comment]
It seems to have been fixed, will reopen the issue if I experience it again 👍
